import img_0 from "./images/img_0.png"
import img_1 from "./images/img_1.png"

const animation1152 = {
  v: "5.6.8",
  fr: 30,
  ip: 0,
  op: 152,
  w: 1152,
  h: 320,
  nm: "val lottie 1152px",
  ddd: 0,
  assets: [
    { id: "image_0", w: 182, h: 230, u: "", p: img_0, e: 0 },
    { id: "image_1", w: 1252, h: 203, u: "", p: img_1, e: 0 },
  ],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 2,
      nm: "barka.png",
      cl: "png",
      parent: 2,
      refId: "image_0",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: {
          a: 1,
          k: [
            {
              i: { x: [0.539], y: [0.585] },
              o: { x: [0.167], y: [0.167] },
              t: 33,
              s: [-177.176],
            },
            {
              i: { x: [0.422], y: [0.98] },
              o: { x: [0.157], y: [-0.502] },
              t: 74,
              s: [-202.599],
            },
            {
              i: { x: [0.664], y: [1] },
              o: { x: [0.331], y: [0] },
              t: 151,
              s: [-189.182],
            },
            { t: 153, s: [-200.176] },
          ],
          ix: 10,
        },
        p: {
          s: true,
          x: { a: 0, k: 27.377, ix: 3 },
          y: { a: 0, k: 13.733, ix: 4 },
        },
        a: { a: 0, k: [94.594, 184.167, 0], ix: 1 },
        s: { a: 0, k: [100, 100, 100], ix: 6 },
      },
      ao: 0,
      ip: 0,
      op: 152,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 3,
      nm: "Trace Shape Layer 2: Path 1 [1.1]",
      cl: "1",
      sr: 1,
      ks: {
        o: { a: 0, k: 0, ix: 11 },
        r: {
          a: 0,
          k: 0,
          ix: 10,
          x:
            "var $bm_rt;\nvar pathToTrace = thisComp.layer('Shape Layer 2')('ADBE Root Vectors Group')(1)('ADBE Vectors Group')(1)('ADBE Vector Shape');\nvar progress = $bm_div(thisLayer.effect('Pseudo/ADBE Trace Path')('Pseudo/ADBE Trace Path-0001'), 100);\nvar pathTan = pathToTrace.tangentOnPath(progress);\n$bm_rt = radiansToDegrees(Math.atan2(pathTan[1], pathTan[0]));",
        },
        p: {
          a: 0,
          k: [576, 160, 0],
          ix: 2,
          x:
            "var $bm_rt;\nvar pathLayer = thisComp.layer('Shape Layer 2');\nvar progress = $bm_div(thisLayer.effect('Pseudo/ADBE Trace Path')('Pseudo/ADBE Trace Path-0001'), 100);\nvar pathToTrace = pathLayer('ADBE Root Vectors Group')(1)('ADBE Vectors Group')(1)('ADBE Vector Shape');\n$bm_rt = pathLayer.toComp(pathToTrace.pointOnPath(progress));",
        },
        a: { a: 0, k: [0, 0, 0], ix: 1 },
        s: { a: 0, k: [100, 100, 100], ix: 6 },
      },
      ao: 0,
      ef: [
        {
          ty: 5,
          nm: "Trace Path",
          np: 4,
          mn: "Pseudo/ADBE Trace Path",
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Progress",
              mn: "Pseudo/ADBE Trace Path-0001",
              ix: 1,
              v: {
                a: 1,
                k: [
                  {
                    i: { x: [0], y: [1] },
                    o: { x: [0.241], y: [0.294] },
                    t: 0,
                    s: [0],
                  },
                  { t: 152, s: [82.111] },
                ],
                ix: 1,
                x:
                  "var $bm_rt;\nif (thisProperty.propertyGroup(1)('Pseudo/ADBE Trace Path-0002') == true && thisProperty.numKeys > 1) {\n    $bm_rt = thisProperty.loopOut('cycle');\n} else {\n    $bm_rt = value;\n}",
              },
            },
            {
              ty: 7,
              nm: "Loop",
              mn: "Pseudo/ADBE Trace Path-0002",
              ix: 2,
              v: { a: 0, k: 1, ix: 2 },
            },
          ],
        },
      ],
      ip: 0,
      op: 152,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 6,
      ty: 4,
      nm: "Shape Layer 1",
      td: 1,
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [576, 160, 0], ix: 2 },
        a: { a: 0, k: [0, 0, 0], ix: 1 },
        s: { a: 0, k: [100, 100, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [130, -181],
                  ],
                  o: [
                    [0, 0],
                    [-119.486, 166.361],
                  ],
                  v: [
                    [-240, 34],
                    [-555, 92],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "st",
              c: {
                a: 0,
                k: [0.113724996529, 0.113724996529, 0.113724996529, 1],
                ix: 3,
              },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 59, ix: 5 },
              lc: 1,
              lj: 1,
              ml: 4,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tm",
              s: { a: 0, k: 99, ix: 1 },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.01], y: [1] },
                    o: { x: [0.167], y: [0.167] },
                    t: 0,
                    s: [0],
                  },
                  { t: 142, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 3,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [0, 0], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Shape 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ty: "gr",
              it: [
                {
                  ind: 0,
                  ty: "sh",
                  ix: 1,
                  ks: {
                    a: 0,
                    k: {
                      i: [
                        [0, 0],
                        [-30, 3],
                      ],
                      o: [
                        [0, 0],
                        [30, -3],
                      ],
                      v: [
                        [102, 75],
                        [200, 2],
                      ],
                      c: false,
                    },
                    ix: 2,
                  },
                  nm: "Path 1",
                  mn: "ADBE Vector Shape - Group",
                  hd: false,
                },
                {
                  ty: "st",
                  c: {
                    a: 0,
                    k: [0.113724996529, 0.113724996529, 0.113724996529, 1],
                    ix: 3,
                  },
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 38, ix: 5 },
                  lc: 1,
                  lj: 1,
                  ml: 4,
                  bm: 0,
                  nm: "Stroke 1",
                  mn: "ADBE Vector Graphic - Stroke",
                  hd: false,
                },
                {
                  ty: "tr",
                  p: { a: 0, k: [0, 0], ix: 2 },
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  r: { a: 0, k: 0, ix: 6 },
                  o: { a: 0, k: 100, ix: 7 },
                  sk: { a: 0, k: 0, ix: 4 },
                  sa: { a: 0, k: 0, ix: 5 },
                  nm: "Transform",
                },
              ],
              nm: "Shape 1",
              np: 2,
              cix: 2,
              bm: 0,
              ix: 1,
              mn: "ADBE Vector Group",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.02], y: [1] },
                    o: { x: [0.167], y: [0.167] },
                    t: 0,
                    s: [100],
                  },
                  { t: 138, s: [12] },
                ],
                ix: 1,
              },
              e: { a: 0, k: 0, ix: 2 },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 2,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [151, 38.5], ix: 2 },
              a: { a: 0, k: [151, 38.5], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 0,
      op: 152,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 7,
      ty: 2,
      nm: "linija bez broda.png",
      cl: "png",
      tt: 2,
      refId: "image_1",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [544, 212, 0], ix: 2 },
        a: { a: 0, k: [626, 101.5, 0], ix: 1 },
        s: { a: 0, k: [100, 100, 100], ix: 6 },
      },
      ao: 0,
      ip: 0,
      op: 152,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
}

export default animation1152
